Repository SpeedyWeather/RainMaker.jl, pull requests merged in 2024-10, with the labels that each got.

#10 RainGauge docs extended
  docs/src/rain_gauge.md
  src/rain_gauge.jl
Labels: documentation

#11 Hourly rate plot too
  docs/src/index.md
  docs/src/rain_gauge.md
Labels: documentation

#19 Adapt to SpeedyWeather v0.12
  Project.toml
  src/rain_gauge.jl
  submissions/aquaplanet.jl
  submissions/atlantic_mountain.jl
  submissions/default.jl
Labels: compatibility

#20 Test with 1.11
  .github/workflows/CI.yml
Labels: testing

#15 Add North Sea submission
  submissions/north_sea_mountain.jl
Labels: submission

#21 rain gauge relative to precip at initialize!
  docs/make.jl
  src/rain_gauge.jl
Labels: bug

#22 More documentation + visualise maps
  docs/make.jl
  docs/src/index.md
  docs/src/new_to_julia.md
  docs/src/rain_gauge.md
  docs/src/submit.md
Labels: documentation
